// <auto-generated />
namespace CodeFirstexistingDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dataAnotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dataAnotations));
        
        string IMigrationMetadata.Id
        {
            get { return "201802272100347_dataAnotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
